name: Deploy Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Prepare files for deployment
      run: |
        # Debug mode
        set -x
        
        # Eenvoudige approach: alles in één map
        echo "Stap 1: Mappen aanmaken"
        mkdir -p deploy_all
        
        # Alleen eenvoudige bestanden maken, geen namespaces
        echo "Stap 2: Super eenvoudige structuur maken"
        
        # Test PHP bestand
        echo '<?php' > deploy_all/test.php
        echo "echo '<h1>Test Pagina</h1>';" >> deploy_all/test.php
        echo "echo '<p>De PHP-server werkt!</p>';" >> deploy_all/test.php
        
        # Info bestand
        echo '<?php' > deploy_all/info.php
        echo "phpinfo();" >> deploy_all/info.php
        
        # Supereenvoudige index zonder namespace
        echo '<?php' > deploy_all/index.php
        echo "echo '<h1>Welkom bij Financieel Beheer</h1>';" >> deploy_all/index.php
        echo "echo '<p>Deze versie is een tijdelijke testversie om de deployment te controleren.</p>';" >> deploy_all/index.php
        echo "echo '<p>Als je deze pagina ziet, werkt de webserver correct!</p>';" >> deploy_all/index.php
        echo "echo '<p><a href=\"test.php\">Test pagina bekijken</a> | <a href=\"info.php\">PHP info bekijken</a></p>';" >> deploy_all/index.php
        
        # .htaccess redirect bestand
        echo "Stap 3: .htaccess maken"
        echo 'RewriteEngine On' > deploy_all/.htaccess
        echo 'RewriteBase /' >> deploy_all/.htaccess
        echo '# PHP Fouten tonen' >> deploy_all/.htaccess
        echo 'php_flag display_errors on' >> deploy_all/.htaccess
        
        # Verifieer de uiteindelijke structuur
        echo "Stap 4: Finale structuur controleren"
        find deploy_all -type f | sort
        
        echo "Super eenvoudige deployment bestanden voorbereid"
    
    - name: FTP Deploy All Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /
        local-dir: ./deploy_all/
        exclude: |
          **/.git*
          **/.git*/**
          .env
          README.md
          .DS_Store

# Hoe te gebruiken:
# 1. Ga naar je GitHub repository
# 2. Klik op Settings > Secrets and variables > Actions
# 3. Voeg de volgende repository secrets toe:
#    - FTP_SERVER: ftp.sunshine.be
#    - FTP_USERNAME: jouw-ftp-gebruikersnaam
#    - FTP_PASSWORD: jouw-ftp-wachtwoord